config/routes.rb
Rails.application.routes.draw do
  
  # root to: "pages#home"
  root to: "articles#index"
  resources :categories
  resources :users
  
  resources :sessions, only: [:index, :create]
  
get 'logout', to: 'sessions#destroy'
  resources :articles do
   
    resources :votes, only: [:create, :destroy]
  end
 
  
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :category_id
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :article_categories, foreign_key: 'article_id'
  has_many :categories, through: :article_categories, dependent: :destroy
  has_many :votes, foreign_key: 'article_id', class_name: 'Vote', dependent: :destroy
  has_one_attached :image
  validates_presence_of :title, :text, :author_id, :image
  validates_length_of :title, :text, { minimum: 3 }

  def self.featured_article
    return unless Vote.any?

    # Find the article with highest vote
    article_id = Vote.group(:article_id).count.max_by { |_k, v| v }.first
    Article.find(article_id)
  end

  def thumbnail
    image.variant(resize: '390x280!').processed
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActionController::Serialization
  before_action :set_article, only: %i[show destroy]
  before_action :current_user

  def index
    @articles = Article.all
    @featured = Article.featured_article
    @categories = Category.order(:priority).limit(4).includes(:articles)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = @current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        # Create article-categories using the category_id and article_id saved
        ArticleCategory.create(category_id: article_params[:category_id], article_id: @article.id)
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        article_category = ArticleCategory.where(article_id: @article.id)
        article_category[0].category_id = article_params[:category_id]
        article_category[0].save
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def featured_title(article)
    article.try(:title)
  end

  def featured_image(article)
    article.try(:image).try(:feature_show).try(:url)
  end

  def featured_content(article)
    article.try { |a| a.text.truncate(100, separator: ' ', omission: '.... (continued)') }
  end

  def number_of_votes(article)
    pluralize(article.votes.size, 'vote')
  end

  def author_name(article)
    article.user.username
  end

  def latest_article_background(category)
    category.articles.last.image if category.articles.any?
  end

  def featured_title_link(article)
    link_to(featured_title(article), article_path(article), class: 'link-title') if article
  end
end

app/views/articles/_form.html.erb
<div class="card">
  <div class="card-header text-center h2 text-muted">
    Life'n'Style
  </div>
  <div class="card-body">
    <%= form_with(model: @article, local: true) do |form| %>
      <%= render 'shared/errors', object: form.object %>
      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control', autofocus: true %>
      </div>
      <div class="field form-group">
        <%= form.label :text %>
        <%= form.text_area :text, class: 'h5 font-weight-bold form-control' %>
      </div>
      <div class="field form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class: 'btn btn-secondary btn-block' %>
      </div>
      <div class="form-group">
        <%= form.label :category_id, 'Category' %>
        <%= form.collection_select :category_id, Category.order(:name), :id, :name, {},{class: "form-control"} %>
      </div>
      <div class="actions">
        <%= form.submit class: 'form-control btn btn-info btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="main-text-color">Editing Article</h1>
  <%= render 'form', article: @article %>
  <%= link_to 'Show Articles', @article %> |
  <%= link_to 'Back To Articles', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="feature-wrapper">
  <% if @articles.collect(&:image).detect(&:attached?) %>
    <div class="featured" style="background-image: url(<%= rails_blob_url(@featured.try(:image).blank? ? 'N/A' : @featured.image) %>);">
      <p class="feature-title"> <%= featured_title_link(@featured) %></p>
      <p class="feature-text"> <%= featured_content(@featured) %></p>
    </div>
  <% end %>
  <div class="img-grid">
    <% @categories.each do |category| %>
      <% if category.articles.collect(&:image).detect(&:attached?) %>
        <div class='category'
             style="background-image: url(<%= rails_blob_url(category.articles.collect(&:image).detect(&:attached?))%>)">
          <p> <%= link_to category.name, category_path(category), class:'text-white font-weight-bold px-2 border-bottom border-warning' %></p>
          <span> <%= category_article_link(category) %></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container mt-5 mb-4">
  <h2 class="text-center h1 mb-3">Create an Article</h2>
  <div class="row">
    <div class="col-md-6 offset-3">
      <%= render 'form', article: @article %>
    </div>
  </div>
  <div class="text-center">
    <%= link_to 'Back To Articles', articles_path, class: 'text-info' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="main-text-color text-center"><%= @article.title %></h1>
  <div class="col-md-12">
    <div class="col-md-6 mb-100 text-center mx-auto">
      <p>Category: <%= @article.categories[0].name %></p>
      <p>
        <h6 class="main-text-color">
          <%= number_of_votes(@article) %>
          <span> for this article</span>
        </h6>
      </p>
      <p class="text-center">
        <%= image_tag(@article.image) %>
      </p>
      <p class="text-left"><%= @article.text %></p>
      <div>
        <% if Vote.find_by(user: @current_user, article: @article) %>
          <%= form_with(url: article_vote_path(@article.id), method: :delete) do |form| %>
            <input type="hidden" name="article_id" value=<% @article.id %>>
            <div class="actions">
              <%= form.submit "UnVote", class: 'btn btn-danger' %>
            </div>
          <% end %>
        <% else %>
          <%= form_with(url: article_votes_path(@article.id)) do |form| %>
            <input type="hidden" name="article_id" value=<% @article.id %>>
            <% if logged_in? %>
              <div class="actions">
                <%= form.submit "Vote", class: 'btn btn-success' %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <%= link_to 'Back To Articles', articles_path %>
      </div>
    </div>
  </div>
</div>