config/routes.rb
Rails.application.routes.draw do
  
  # root to: "pages#home"
  root to: "articles#index"
  resources :categories
  resources :users
  
  resources :sessions, only: [:index, :create]
  
get 'logout', to: 'sessions#destroy'
  resources :articles do
   
    resources :votes, only: [:create, :destroy]
  end
 
  
end

app/views/shared/_errors.html.erb
<%# <% if object.errors.any? %>
<%# <ul class="errors alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
  <%# <li> <%= msg %> </li>
<%# <% end %>
<%# </ul> %>
<%# <% end %>
<% if object.errors.any? %>
  <div class="error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path, class: "navbar-brand text-white"  do %>
    <i class="fa fa-language" aria-hidden="true"></i> Life'n'Style
  <% end %>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "Privacy Policy", root_path, class: "nav-link rules" %>
    </li>
    <li class="nav-item">
      <%= link_to "Terms & Conditions", root_path, class: "nav-link rules" %>
    </li>
    <li class="nav-item">
      <%= link_to "Copyright 2020. All rights reserved", root_path, class: "nav-link" %>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0 ml-auto">
    <!-- Nav Icons -->
    <div class="navbar-nav footer-info">
      <li><span class='text-white'>Connect with us: </span></li>
      <li class="nav-item border rounded-circle mx-2 search-icon">
        <%= link_to "<i class='fa fa-twitter social-icons'></i>".html_safe, '#' %>
      </li>
      <li class="nav-item border rounded-circle mx-2 search-icon">
        <%= link_to "<i class='fa fa-instagram social-icons'></i>".html_safe, '#' %>
      </li>
      <li class="nav-item border rounded-circle mx-2 search-icon">
        <%= link_to "<i class='fa fa-facebook social-icons'></i>".html_safe, '#' %>
      </li>
    </div>
  </form>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand"  do %>
    <i class="fa fa-language" aria-hidden="true"></i> Life'n'Style
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <%= nav_items(@nav_categories) %>
    </ul>
    <form class="form-inline my-2 my-lg-0 ml-auto">
      <% if @current_user.nil? %>
        <%= link_to "Log In",  sessions_path, class: "nav-link  my-2 my-sm-0 mr-3" %>|
        <%= link_to "Register",   new_user_path, class: "nav-link  my-2 my-sm-0" %>
        <%= link_to root_path, class: "nav-link"  do %>
          <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      <% else %>
        <%= link_to "Log Out",  logout_path, method: :delete, data: {:confirm => 'Are you sure?'}, class: "nav-link btn btn-outline-danger my-2 my-sm-0 mr-3" %>
      <% end %>
    </form>
  </div>
</nav>
</div>