config/routes.rb
Rails.application.routes.draw do
  
  # root to: "pages#home"
  root to: "articles#index"
  resources :categories
  resources :users
  
  resources :sessions, only: [:index, :create]
  
get 'logout', to: 'sessions#destroy'
  resources :articles do
   
    resources :votes, only: [:create, :destroy]
  end
 
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, foreign_key: 'category_id'
  has_many :articles, through: :article_categories, dependent: :destroy
  validates_presence_of :name, :priority
  validates_length_of :name, { minimum: 3 }
  validates_uniqueness_of :priority
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ActionController::Serialization
  before_action :set_category, only: %i[show edit update destroy]
  before_action :current_user

  def index
    @categories = Category.all
  end

  def show
    @category_articles = @category.articles.order('id DESC').limit(4)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def vote_button(article)
    vote = Vote.find_by(user: @current_user, article: article)

    if vote
      link_to('UnVote', article_vote_path(id: vote.id, article_id: article.id),
              method: :delete, class: 'btn btn-danger')
    else
      link_to('Vote', article_votes_path(article.id), remote: true, method: :post, class: 'btn btn-success')
    end
  end

  def category_article_title(article)
    article.title.truncate(27)
  end

  # @articles.collect(&:image).detect(&:attached?)
  def category_article_text(article)
    article.text.truncate(100, separator: ' ', omission: '.... (continued)')
  end

  def category_article_link(category)
    return unless category.articles.any?

    link_title = category.articles.pluck(:title).last.truncate(27)
    article = category.articles.last
    link_to(link_title, article_path(article), class: 'link-title underline')
  end
end

app/views/categories/_form.html.erb
<div class="card">
  <div class="card-header text-center h2 text-muted">
    Life'n'Style
  </div>
  <div class="card-body">
    <%= form_with(model: category, local: true) do |form| %>
      <% if category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
          <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= form.label :priority %>
        <%= form.number_field :priority, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit class: 'form-control btn btn-danger btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="d-flex justify-content-between">
    <h1>Categories</h1>
    <p><%= link_to 'New Category', new_category_path, class: 'btn btn-outline-danger' %></p>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Priority</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.priority %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/categories/new.html.erb
<div class="container mt-5 mb-4">
  <h2 class="text-center h1 mb-3">Create New Category</h2>
  <div class="row">
    <div class="col-md-4 offset-4">
      <%= render 'form', category: @category %>
    </div>
  </div>
</div>
<div class="text-center mb-4">
  <%= link_to 'Back To Categories', categories_path, class: 'btn btn-outline-info' %>
</div>

app/views/categories/show.html.erb
<div class="grid-container mt-0">
  <% @category_articles.each_with_index do |article, index| %>
    <div>
      <% if article.image.attached? %>
        <div class="img">
          <%= image_tag(article.thumbnail) if index.odd? %>
        </div>
      <% end %>
      <div class="content">
        <div>
          <div class="card-body mb-0">
            <h5 class="main-text-color underline cat_name-color w-25"><%= @category.name %></h5>
            <h6 class="mb-2 text-muted"><%= link_to category_article_title(article), article_path(article), class: 'cat_name-color' %></h6>
            <p class="mb-0"><%= category_article_text(article) %></p>
            <p><%= link_to "Read More", article, class: 'text-light-orange' %> </p>
            <div class="d-flex justify-content-between mb-0">
              <span class="main-text-color card-link"><%= number_of_votes(article) %> </span>
              <%# <%= vote_button(article) if @current_user  %>
              <% if Vote.find_by(user: @current_user, article: article) %>
                <%= form_with(url: article_vote_path(article.id), method: :delete) do |form| %>
                  <input type="hidden" name="article.id" value=<% article.id %>>
                  <div class="actions">
                    <%= form.submit "UnVote", class: 'btn btn-danger' %>
                  </div>
                <% end %>
              <% else %>
                <%= form_with(url: article_votes_path(article.id)) do |form| %>
                  <input type="hidden" name="article_id" value=<% article.id %>>
                  <% if logged_in? %>
                    <div class="actions">
                      <%= form.submit "Vote", class: 'btn btn-success' %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% if article.image.attached? %>
        <%= image_tag(article.thumbnail) if index.even? %>
      <% end %>
    </div>
  <% end %>
</div>